### ISSUE TITLE
Error installing fs-constants

### ISSUE THREAD

**Issue by divitrao** [mafintosh/fs-constants#2]
using node 21.4.0 & npm 10.2.4

```
npm WARN tar TAR_BAD_ARCHIVE: Unrecognized archive format
npm WARN tar TAR_BAD_ARCHIVE: Unrecognized archive format
npm ERR! code TAR_BAD_ARCHIVE
npm ERR! TAR_BAD_ARCHIVE: Unrecognized archive format
```

**Comment by vipin14444** [comment]
Facing something similar to this while building my nextjs project.

**Comment by bhushan629-inspacco** [comment]
I am also facing same issue

**Comment by bhushan629-inspacco** [comment]
If anyone facing this issue try creating `.npmrc` file and add below line
`registry=https://registry.npmmirror.com/`

This will fix the issue

**Comment by gomesLuis479SV** [comment]
same here

**Comment by omkarpai** [comment]
same here

**Comment by ronakrrb** [comment]
@bhushan629-inspacco The solution worked but it change the resolved url for all the packages in the yarn.lock file. Is it safe?

**Comment by kshitijjolly-probo** [comment]
> If anyone facing this issue try creating `.npmrc` file and add below line `registry=https://registry.npmmirror.com/`
> 
> This will fix the issue

This will be better if issue is only with fs-constants -
```
fs-constants:registry=https://registry.npmmirror.com/
```

**Comment by Zayed4321** [comment]
> > If anyone facing this issue try creating `.npmrc` file and add below line `registry=https://registry.npmmirror.com/`
> > This will fix the issue
> 
> This will be better if issue is only with fs-constants -
> 
> ```
> fs-constants:registry=https://registry.npmmirror.com/
> ```

So will it come to no use trying this method of using another registry for downloading the packages?

**Comment by Riddhish97** [comment]
> fs-constants:registry=https://registry.npmmirror.com/

Yes, changing the registry fixed the issue, but my main concern is that npmmirror.com is a Chinese registry, so I'm not sure about using it.

Another thing is that this same package was properly downloaded by my colleague in Brazil. According to npm, this package hasn't been updated in the past seven years.

**Comment by 7kms** [comment]
It seems there are issues with the NPM CDN server in Mumbai, India.

Please check the official status updates here: https://status.npmjs.org/

In the meantime, you can temporarily resolve this issue by changing the registry origin as follows and wait for an official fix from NPM:
```
npm config set registry https://registry.npmmirror.com/
```

**Comment by vipin14444** [comment]
This issue is resolved as the npm registry is working now.
