### ISSUE TITLE
Nextjs build fail "Error: https://registry.yarnpkg.com/fs-constants/-/fs-constants-1.0.0.tgz: Request failed "304 Not Modified""

### ISSUE THREAD

**Issue by vipin14444** [mafintosh/fs-constants#3]
Build process is failing with the below mentioned trace:

```console
yarn install v1.22.22
30 | [1/4] Resolving packages...
31 | [2/4] Fetching packages...
32 | error Error: https://registry.yarnpkg.com/fs-constants/-/fs-constants-1.0.0.tgz: Request failed "304 Not Modified"
33 | at ResponseError.ExtendableBuiltin (/usr/local/lib/node_modules/yarn/lib/cli.js:696:66)
34 | at new ResponseError (/usr/local/lib/node_modules/yarn/lib/cli.js:802:124)
35 | at Request.<anonymous> (/usr/local/lib/node_modules/yarn/lib/cli.js:66750:16)
36 | at Request.emit (node:events:517:28)
37 | at module.exports.Request.onRequestResponse (/usr/local/lib/node_modules/yarn/lib/cli.js:142287:10)
38 | at ClientRequest.emit (node:events:517:28)
39 | at HTTPParser.parserOnIncomingClient (node:_http_client:700:27)
40 | at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
41 | at TLSSocket.socketOnData (node:_http_client:541:22)
42 | at TLSSocket.emit (node:events:517:28)
43 | info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
44 |  
45 | [Container] 2024/12/17 08:27:39.925196 Command did not exit successfully yarn install exit status 1
46 | [Container] 2024/12/17 08:27:39.936945 Phase complete: BUILD State: FAILED
47 | [Container] 2024/12/17 08:27:39.936960 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: yarn install. Reason: exit status 1
```

Node: v22.9.0

**Comment by bhushan629-inspacco** [comment]
If anyone facing this issue try creating `.npmrc` file and add below line
`registry=https://registry.npmmirror.com/`

This will fix the issue

**Comment by ronakrrb** [comment]
@bhushan629-inspacco The solution worked but it changed the resolved url for all the packages in the yarn.lock file. Is it safe?

**Comment by bhushan629-inspacco** [comment]
> @bhushan629-inspacco The solution worked but it changed the resolved url for all the packages in the yarn.lock file. Is it safe?

For now use this registry as npm registry has issues. once that is fixed, you can revert this back
https://github.com/npm/cli/issues/7986

**Comment by vipin14444** [comment]
> If anyone facing this issue try creating `.npmrc` file and add below line `registry=https://registry.npmmirror.com/`
> 
> This will fix the issue

I am using yarn. I tried creating .yarnrc but it is still not working.

.yarnrc
`
registry "https://registry.npmmirror.com/"
`

**Comment by vaibhavi3t** [comment]
> registry=https://registry.npmmirror.com/

Avoid using this registry until you are 100% sure. It is Chinese registry and cause pose potential threat.

**Comment by JohnSyoft** [comment]
Thanks it worked

**Comment by Ramesh0807** [comment]
I am also facing the same problem while building code and installing

**Comment by karthik-minnikanti** [comment]
I’m facing the same issue. Has anyone tried a working alternative solution other than changing the registry URL?

**Comment by Ramesh0807** [comment]
Temporary Solution for the Issue:

To resolve the issue temporarily, follow these steps:

    1.Copy the fs-constant folder.
    2.Paste it into your node_modules directory.

This should temporarily resolve the problem
[fs-constants-1.0.0..zip](https://github.com/user-attachments/files/18167084/fs-constants-1.0.0.zip)

**Comment by vipin14444** [comment]
This issue is resolved as the npm registry is working now.
